# YAML Configuration file for the network

# layers can be chosen in {Linear, MultiHeadAttention, Sum, MLP}
# Dimensions to give:
#   - Linear (input, output)
#   - MultiHeadAttention (width)
#   - Sum ()
#   - MLP (input, width, ... , width, output)
Network_parameters:
  Encoder:
    layers: ["Linear", "MultiHeadAttention", "MultiHeadAttention", "MultiHeadAttention", "Sum", "Linear"]
    dimensions: [[2, 64], [64], [64], [64], [], [64, 64]]
    latent_dimension: 100
  Decoder:
    layers: ["Linear", "MultiHeadAttention", "MultiHeadAttention", "MultiHeadAttention", "Linear"]
    dimensions: [[102, 64], [64], [64], [64], [64, 2]]
  MultiHeadAttention:
    n_head: 3
    head_width: 32
  # Chamfer, Hungarian, HungarianVAE, ChamferVAE
  Loss: "ChamferVAE"

Baseline_parameters:
  Encoder:
    layers: ["MLP", "Sum", "Linear"]
    dimensions: [[2, 32, 32, 32 ,32], [], [32, 4]]
  Decoder:
    layers: ["MLP"]
    dimensions: [[6, 32, 32 ,32, 2]]

DataSet_parameters:
  # CovMatrix or RecTriangle
  type: "CovMatrix"
  size: 100
  n_points: 80
  n_feature: 2

Run_parameters:
  wandb: True
  baseline: False

