# YAML Configuration file for the network

# layers can be chosen in {Linear, MultiHeadAttention, Sum, MLP}
# Dimensions to give:
#   - Linear (input, output)
#   - MultiHeadAttention (width)
#   - Sum ()
#   - MLP (input, width, ... , width, output)
Network_parameters:
  Encoder:
    layers: ["Linear", "MultiHeadAttention", "Sum", "Linear"]
    dimensions: [[2, 32], [32], [], [32, 32]]
    latent_dimension: 5
  Decoder:
    layers: ["Linear", "MultiHeadAttention", "Linear"]
    dimensions: [[7, 32], [32], [32, 2]]
  MultiHeadAttention:
    n_head: 3
    head_width: 32

DataSet_parameters:
  size: 1000
  n_points: 3
  n_feature: 2
