# YAML Configuration file for the network

Network_parameters:
  Encoder:
    n_layers: 3
    hidden_width: 12
    latent_dimension: 8
  Transformer:
    n_layers: 2
    weight_sharing: False
    normalization: False
    Feed_forward:
      hidden_width: 16
      n_layers: 3
    MultiHeadAttention:
      n_heads: 2
      head_width: 4
      dropout: 0.1

# Type of dataset to choose between RecTriangle, CovMatrixSet
DataSet_parameters:
  type: "RecTriangle"
  size: 1
  n_points: 3
  n_feature: 2
